# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
# version: 0.2
# phases:
#   pre_build:
#     commands:
#       - echo Installing source NPM dependencies...
#       - npm install
#   build:
#     commands:
#       - echo Build started on `date`
#       - echo Compiling the dist folder

#   post_build:
#     commands:
#       - echo Build completed on `date`
# Include only the files required for your application to run.
# artifacts:
#   files:
#     - index.js
#     - dist/**/*
#     - request-map.js
#     - credentials.json
#     - node_modules/**/*

version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login --username springworks2905 --password d2946b34-795d-400b-9aa5-506a616b73a4
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $SERVICE_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
